### ISSUE TITLE
Add Unit Tests for FASTQ generator

### ISSUE THREAD

**Issue by vaastav** [Lab41/hypothesis-bio#10]

**Comment by vaastav** [comment]
Quoting @luizirber 
" This repo is a treasure trove of valid and invalid examples for bioinformatics file formats: https://github.com/BioJulia/BioFmtSpecimens

Might be good to check the FASTQ examples to see how to generate good (and bad) inputs here."

**Comment by mbhall88** [comment]
If ok with everyone else I will work on this to get up to speed with the testing framework

**Comment by vaastav** [comment]
@mbhall88 Sounds good. I will write tests for FASTA in the meanwhile.
