### ISSUE TITLE
FASTQ

### ISSUE THREAD

**Issue by Benjamin-Lee** [Lab41/hypothesis-bio#2]
We should have a strategy that generates FASTQ string such as:
```
@SEQ_ID
GATTTGGGGTTCAAAGCAGTATCGATCAAATAGTAAATCCATTTGTTCAACTCACAGTTT
+
!''*((((***+))%%%++)(%%%%).1***-+*''))**55CCF>>>>>>CCCCCCC65
```

**Comment by vaastav** [comment]
Quality value characters for FASTQ format (in ASCII format):
 !"#$%&'()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_`abcdefghijklmnopqrstuvwxyz{|}~

**Comment by vaastav** [comment]
Implemented in PR #4

**Comment by mbhall88** [comment]
I don't think this should be closed until we have unit tests for this function.

**Comment by Benjamin-Lee** [comment]
I'll get on figuring out how to unit test our code now

**Comment by Benjamin-Lee** [comment]
Just pushed a better set of unit tests for DNA with a new `minimal` function, which returns the smallest example of a given strategy.

**Comment by Benjamin-Lee** [comment]
Great catch on the mutable arguments. I originally got the prototype working by copying [hypothesis-networkx](https://github.com/pckroon/hypothesis-networkx/blob/master/hypothesis_networkx/strategy.py).

**Comment by vaastav** [comment]
> I don't think this should be closed until we have unit tests for this function.

I think we should have separate issues for the unit tests. Having fine-grained issues would better help in tracking of tasks.

**Comment by luizirber** [comment]
This repo is a treasure trove of valid and invalid examples for bioinformatics file formats: https://github.com/BioJulia/BioFmtSpecimens

Might be good to check the FASTQ examples to see how to generate good (and bad) inputs here.

**Comment by vaastav** [comment]
I have opened Issue #10 for adding unit tests for FASTQ generator.
I am closing this issue.
