### ISSUE TITLE
hackseq review

### ISSUE THREAD

**Issue by nknoetze** [Lab41/hypothesis-bio#31]
Cool idea!! I can't even count how many times scripts haven't worked from the smallest bug that are hard to catch by eye. The examples were simple and concise which helped with understanding the concept.

A few questions:
What may be some limitations to hypothesis-bio? Are there any situations that it is not able to test for?
I'm also curious how many given's you can provide to Hypothesis-bio, and if any point it becomes repetitive to provide every possible given.

Looking forward to the updates!

**Comment by Benjamin-Lee** [comment]
Thanks @nknoetze!
