### ISSUE TITLE
Do you want to merge projects?

### ISSUE THREAD

**Issue by luizirber** [Lab41/hypothesis-bio#6]
I started this during PyCon sprints this year:
https://github.com/luizirber/hypothesis-bio/
and I'm totally OK in contributing with yours instead =]

**Comment by Benjamin-Lee** [comment]
Oh wow, I didn't see your project at all. My mistake!

Did you end up putting it on PyPI? I searched for `hypothesis-bio` and looked at all the projects with the [`Framework :: Hypothesis`](https://pypi.org/search/?q=&c=Framework+%3A%3A+Hypothesis) trove classifier before starting this project and didn't find it. I should have searched GitHub!

We'll be working on this project over the weekend at [hackseq](https://www.hackseq.com/hackseq19). @mbhall88 will be remote, so if you're interested in joining the team, it's definitely possible. Also if you're ok with us stealing/adopting/merging your code, I'd definitely appreciate it and will be sure to credit you.

**Comment by luizirber** [comment]
My bad, I should have published it before...

Hmm, can I participate without being enrolled in hackseq?

**Comment by Benjamin-Lee** [comment]
Sure, which email do you want me to use? We're a small team (four people total), so I don't think there'll be any issue adding one more person.
