### ISSUE TITLE
Refactor strategies into separate files

### ISSUE THREAD

**Issue by mbhall88** [Lab41/hypothesis-bio#68]
Copying the [`hypothesis`](https://github.com/HypothesisWorks/hypothesis/tree/master/hypothesis-python) structure to some degree might be a good way of doing this.

**Comment by Benjamin-Lee** [comment]
What about something like:

```
hypothesis_bio/
  README.md
  tests/
  hypothesis_bio/
    fasta.py
    dna.py
    .
    .
    .
```

**Comment by mbhall88** [comment]
I kind of like the way they have it set up in hypothesis in that it's quite clear in the code that you are importing a strategy.

I'd like to be able to do

```py
from hypothesis-bio.strategies import fastq
```

**Comment by Benjamin-Lee** [comment]
This might be a dumb question, but what's the value of having a separate strategies module if there isn't a non-strategy module?

I.e. why not:

`from hypothesis_bio import fastq`

**Comment by Benjamin-Lee** [comment]
In support of your design, I will add that hypothesis-csv is imported from the strategies module

**Comment by mbhall88** [comment]
> This might be a dumb question, but what's the value of having a separate strategies module if there isn't a non-strategy module?
> 
> I.e. why not:
> 
> `from hypothesis_bio import fastq`

Yeah, fair point.
