### ISSUE TITLE
Can we drop Blast6 for hypothesis-csv?

### ISSUE THREAD

**Issue by Benjamin-Lee** [Lab41/hypothesis-bio#72]
It seems that [hypothesis-csv](https://github.com/chobeat/hypothesis-csv) already has pretty good support for generating tab-delimited files. Would it make sense to drop our blast6 implementation and add a section in the docs referring users to hypothesis-csv (maybe with an example)?

**Comment by vaastav** [comment]
Hmm, maybe. The thing is we have specific rules for generating specific columns but I think they can be supported via hypothesis-csv....

So, I would say it makes sense to drop blast6 and just add docs redirecting users to hypothesis-csv.

**Comment by Benjamin-Lee** [comment]
Ok that sounds good to me
