### ISSUE TITLE
Port strategies from luizirber's hypothesis repo

### ISSUE THREAD

**Issue by vaastav** [Lab41/hypothesis-bio#8]
There are a couple of different strategies available at https://github.com/luizirber/hypothesis-bio that we should port.
Specifically, kmer seems to be one that would make sense to port

**Comment by luizirber** [comment]
There is also an open PR with a coding sequence generator by @arendsee that was never merged (my fault again, sorry!)
https://github.com/luizirber/hypothesis-bio/pull/2

I'll also tag @Zac-HD here, so he's aware that a new hypothesis-bio effort is in full swing =]

**Comment by vaastav** [comment]
There already is a strategy for generating coding sequences I believe.

**Comment by Zac-HD** [comment]
> I'll also tag @Zac-HD here, so he's aware that a new hypothesis-bio effort is in full swing =]

🎉 

I remain very happy to review any open-source code using Hypothesis, FYI, especially in science.  Just tag me 😁

**Comment by Zac-HD** [comment]
And, uh, I assume that https://pypi.org/project/hypothesis-bio/ will reliably be the thing that I should point people to?  Because it's currently pointing to @luizirber's repo...

**Comment by Benjamin-Lee** [comment]
@luizirber, can we use the PyPI handle for this project?

**Comment by luizirber** [comment]
This repo should take over the PyPI handle, once there is a release...
